global:
    scrape_interval: 5s
scrape_configs:
    - job_name: "prometheus"
      static_configs:
        - targets: ["mainmetodology-api:5002"]
    - job_name: "rabbitmq"
      static_configs:
        - targets: ["rabbitmq:15692"]
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']
    
rule_files:
  - "alert_rules.yml"
