on:
    push:
        branches: [dev, dev1, wip/*, main]
    pull_request:
        branches: [main]
    workflow_dispatch:
env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup .NET 8
              uses: actions/setup-dotnet@v3
              with: 
                dotnet-version: '8.0.x'
            
            # - name: Generate appsettings.json
            #   run: |
            #     (Get-Content ./MeethodologyMain.API/appsettings.Template.json) -replace '#{POSTGRES_CONNECTION_STRING}#', '${{ secrets.POSTGRES_CONNECTION_STRING }}' -replace '#{GOOGLE_CLIENT_ID}#', '${{ secrets.GOOGLE_CLIENT_ID }}' -replace '#{JWT_SECRET_KEY}#', '${{ secrets.JWT_SECRET_KEY }}' | Set-Content ./AuthMetodology/appsettings.json
            #   shell: pwsh

            - name: Restore dependencies
              run: dotnet restore --verbosity quiet ./MethodologyMain.sln

            - name: Build without warnings
              run: dotnet build --configuration Release --no-restore ./MethodologyMain.sln

            # - name: Run tests
            #   run: dotnet test --verbosity normal

            - name: Upload test results
              if: always()
              uses: actions/upload-artifact@v4
              with: 
                name: test-results
                path: '**/*.trx'
            
